SET DATABASE SQL SYNTAX ORA TRUE;

CREATE SCHEMA SINTERKLAAS;
SET INITIAL SCHEMA SINTERKLAAS;

CREATE SEQUENCE SINTERKLAAS."PERSON.SEQ";

--  DDL for Table CLIENT_TYPE
CREATE TABLE SINTERKLAAS."TEMPLATE"
("ID"       DECIMAL,
 "NAME"     VARCHAR(255),
 "TEXT"     CLOB
);

INSERT INTO SINTERKLAAS."TEMPLATE"(ID, NAME, TEXT) VALUES (1, 'DUMMY_TEMPLATE_1', 'DUMMY_TEXT');