SET DATABASE SQL SYNTAX ORA TRUE;
CREATE SCHEMA MANAGER;
SET INITIAL SCHEMA MANAGER;

CREATE SEQUENCE MANAGER."PERSON.SEQ";

--  DDL for Table CLIENT_TYPE
CREATE TABLE MANAGER."PERSON"
("ID"             DECIMAL,
 "FIRST_NAME"     VARCHAR(255),
 "LAST_NAME"      VARCHAR(255)
);

INSERT INTO MANAGER."PERSON"(ID, FIRST_NAME, LAST_NAME) VALUES (1, 'LUCA', 'FILIPPONE');